-- CREATE TABLE papers (
--     id SERIAL PRIMARY KEY,
--     paper_type VARCHAR(100),
--     paper_weight VARCHAR(20),
--     paper_description VARCHAR(200),
--     multiplier FLOAT,
--     category ENUM('Fine Art', 'Photo') DEFAULT 'Fine Art'
-- );

-- INSERT INTO papers (paper_type, paper_weight, paper_description, multiplier, category) VALUES
--     ('Hahnemühle Photo Rag Ultrasmooth', '305 gsm', N'Smooth Matte Finish - Hot Press', 23.0, 'Fine Art'),
--     ('Hahnemühle William Turner Watercolor', '308 gsm', N'Mould-Made - Cold Press - Textured', 23.0, 'Fine Art'),
--     ('Hahnemühle Photo Rag Satin', '310 gsm', N'Subtle sheen in printed areas - Slight texture', 23.0, 'Fine Art'),
--     ('Hahnemühle Photo Rag Pearl', '320 gsm', N'Luster finish, Vibrant colors - Slight texture', 23.0, 'Fine Art'),
--     ('Hahnemühle Photo Rag Metallic', '340 gsm', N'The only cotton rag paper w/ a silver metallic base. Excellent for BW or color', 24.0, 'Fine Art'),
--     ('Hahnemühle Photo Rag Baryta Gloss', '320 gsm', N'High Gloss finish, Vibrant colors – Slight texture', 23.0, 'Fine Art'),
--     ('Arches Aquarelle Watercolor', '240 gsm', N'Mould-Made - Cold Press - Textured', 20.5, 'Fine Art'),
--     ('BFK Rives Watercolor', '310 gsm', N'Mould-Made - Cold Press - Textured', 20.5, 'Fine Art'),
--     ('Somerset Enhanced Velvet Watercolor', '255 gsm', N'Mould-Made - Cold Press - Textured', 18.0, 'Fine Art'),
--     ('Moenkopi Unryu Fiber', '55 gsm (Rice Paper)', N'Long-Fiber Washi Paper', 18.0, 'Fine Art'),
--     ('Canson Baryta Photographique II', '345 gsm', N'100% Acid-Free Cellulose, Barium Sulfate, Clay-Coated, Smooth, Bright White, Gloss: Amazing Color & Durability', 15.0, 'Photo'),
--     ('Epson Smooth Luster', '280 gsm', N'Standard Luster (Semi-Gloss) Photo Paper', 9.5, 'Photo'),
--     ('Heavyweight Matte Poster - Bright White, Acid-Free', '230 gsm', N'Posters & Graphics', 9.5, 'Photo'),
--     ('Phototex Wallcovering (Repositionable, Adhesive-Backed) 24” or 42” Wide Sections', '', N'Photo Murals - Signage', 12.5, 'Photo'),
--     ('Hemp-Agave-Sugar Cane Bamboo','','Natural Line',20.0,'Photo'),
--     ('Bamboo Gloss Baryta','','Natural Line',21.0,'Photo');